### PR TITLE
Update compilation instructions

### LINKED ISSUE #6: Package make compile error
After running the steps in `README.md` and then running `make` command I get the following error:

```
Generating index for package ./libgcc1_7.5.0-2_arm_cortex-a9_vfpv3-d16.ipk
Generating index for package ./libpthread_1.1.24-2_arm_cortex-a9_vfpv3-d16.ipk
Generating index for package ./librt_1.1.24-2_arm_cortex-a9_vfpv3-d16.ipk
Generating index for package ./libstdcpp6_7.5.0-2_arm_cortex-a9_vfpv3-d16.ipk
Signing package index...
Cannot open file '/home/alex/Projects/openwrt-sdk-19.07.10-mvebu-cortexa9_gcc-7.5.0_musl_eabi.Linux-x86_64/key-build' for reading
Cannot open file '/home/alex/Projects/openwrt-sdk-19.07.10-mvebu-cortexa9_gcc-7.5.0_musl_eabi.Linux-x86_64/key-build' for reading
Cannot open file '/home/alex/Projects/openwrt-sdk-19.07.10-mvebu-cortexa9_gcc-7.5.0_musl_eabi.Linux-x86_64/key-build' for reading
make[2]: *** [package/Makefile:85: package/index] Error 1
make[2]: Leaving directory '/home/alex/Projects/openwrt-sdk-19.07.10-mvebu-cortexa9_gcc-7.5.0_musl_eabi.Linux-x86_64'
make[1]: *** [Makefile:55: world] Error 2
make[1]: Leaving directory '/home/alex/Projects/openwrt-sdk-19.07.10-mvebu-cortexa9_gcc-7.5.0_musl_eabi.Linux-x86_64'
make: *** [/home/alex/Projects/openwrt-sdk-19.07.10-mvebu-cortexa9_gcc-7.5.0_musl_eabi.Linux-x86_64/include/toplevel.mk:220: world] Error 2
```

The problem is that the that the package signing key is missing.

Solution is to update the documentation.

### LINKED ISSUE #7: Update the compilation docs
The docs do not explain how to compile the packages. `make defconfig` only generate the config files.

### PR DESCRIPTION
**Pull request by aloisklink**
Adds all the bash commands that need to be run to compile ManySecured packages.

Fixes #6, fixes #7

### CODE REVIEW

**Comment by mereacre** [comment]
Using openwrt-sdk-19.07.10-mvebu-cortexa9_gcc-7.5.0_musl_eabi.Linux-x86_64 where's the compiled `edgesec` package located after running the `make` command?

**Comment by aloisklink** [comment]
> where's the compiled edgesec package located after running the make command?

Good catch! The compiled `.ipk` files can be found in `bin/packages/*/manysecured` (replacing `*` with your architecture/target)!

E.g.

```console
alois@me:~/many-secured/deployment$ ls sdk-19.07-cortexa9/bin/packages/arm_cortex-a9_vfpv3-d16/manysecured
edgesec_0.0.8-1_arm_cortex-a9_vfpv3-d16.ipk  Packages  Packages.gz  Packages.manifest  Packages.sig
```

I added a new commit with documentation in https://github.com/nqminds/manysecured-openwrt-packages/pull/8/commits/f1e052f9aacef4128054cb4bb129d838b9012d2b

Btw Alex, if you're compiling packages for Turris OS, I highly recommend using the instructions here: https://github.com/nqminds/many-secured/tree/main/deployment

**Packages built for OpenWRT are not compatible with Turris OS** (although I believe it does work the other way around)

**Comment by mereacre** [comment]
I'am compiling for the `arm_cortex-a9_vfpv3-d16` architecture, but it doesn't seem to be compiling any packages. Here is the tree output after running `make`:

```
$ tree
.
└── arm_cortex-a9_vfpv3-d16
    ├── base
    │   ├── Packages
    │   ├── Packages.gz
    │   ├── Packages.manifest
    │   └── Packages.sig
    └── node
        ├── Packages
        ├── Packages.gz
        ├── Packages.manifest
        └── Packages.sig

3 directories, 8 files
```

**Comment by mereacre** [comment]
Looks like I didn't add `src-git manysecured https://github.com/nqminds/manysecured-openwrt-packages.git`. Will test now.

**Comment by aloisklink** [comment]
Ah, that's my fault :facepalm: 

Try replacing the line in your `feeds.conf` or `feeds.conf.default` file with:

```conf
src-git manysecured https://github.com/nqminds/manysecured-openwrt-packages.git
```

I accidentally wrote it as `node`, not `manysecured`.

Then make sure to rerun `./scripts/feeds install -a -p manysecured` to enable compiling the manysecured packages.

**Comment by mereacre** [comment]
```bash
$ ./scripts/feeds install -a -p manysecured
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'r8169-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'e100-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'bnx2-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'ar3k-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'mwifiex-sdio-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'kmod-phy-bcm-ns-usb2', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'edgeport-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'kmod-phy-bcm-ns-usb3', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'amdgpu-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'radeon-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'prism54-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'rtl8192su-firmware', which does not exist
Ignoring feed 'node' - index missing
Ignoring feed 'manysecured' - index missing
Installing all packages from feed manysecured.
Ignoring feed 'manysecured' - index missing
```

Still doesn't compile anythting.

**Comment by aloisklink** [comment]
```console
alois@me:~/manysecured-openwrt-packages/openwrt-sdk-19.07.10-mvebu-cortexa9_gcc-7.5.0_musl_eabi.Linux-x86_64$ ./scripts/feeds install -a -p manysecured
Collecting package info: done
Collecting target info: done
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'r8169-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'e100-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'bnx2-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'ar3k-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'mwifiex-sdio-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'kmod-phy-bcm-ns-usb2', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'edgeport-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'kmod-phy-bcm-ns-usb3', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'amdgpu-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'radeon-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'prism54-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'rtl8192su-firmware', which does not exist
Installing all packages from feed manysecured.
Installing package 'edgesec' from manysecured
Installing package 'hostapd' from base
Installing package 'libnl-tiny' from base
Installing package 'ubus' from base
Installing package 'libubox' from base
Installing package 'lua' from base
Installing package 'libjson-c' from base
Installing package 'openssl' from base
Installing package 'zlib' from base
Installing package 'cryptodev-linux' from base
Installing package 'wolfssl' from base
Installing package 'libtool' from base
Installing package 'gettext' from base
Installing package 'libiconv' from base
Installing package 'dnsmasq' from base
Installing package 'nettle' from base
Installing package 'gmp' from base
Installing package 'libnetfilter-conntrack' from base
Installing package 'libnfnetlink' from base
Installing package 'libmnl' from base
Installing package 'util-linux' from base
Installing package 'ncurses' from base
Installing package 'uci' from base
Installing package 'sqlite3' from packages
Installing package 'libedit' from packages
Installing package 'readline' from base
Installing package 'libpcap' from base
```

Hmmm, it seems to work for me. Can you try deleting the SDK folder, then re-extracting it from the `.tar.xz` file, editing `feeds.conf.default`, and running all the commands again? I wonder if something broke in all the edits.

**Comment by mereacre** [comment]
After I do the below I get:
```bash
$ ./scripts/feeds update
Updating feed 'manysecured' from 'https://github.com/nqminds/manysecured-openwrt-packages.git' ...
Cloning into './feeds/manysecured'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 11 (delta 0), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (11/11), 4.85 KiB | 414.00 KiB/s, done.
Create index file './feeds/manysecured.index' 
Collecting package info: done
Collecting target info: done
```

Then this:
```bash
$ ./scripts/feeds install -a -p manysecured
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'r8169-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'e100-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'bnx2-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'ar3k-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'mwifiex-sdio-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'kmod-phy-bcm-ns-usb2', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'edgeport-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'kmod-phy-bcm-ns-usb3', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'amdgpu-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'radeon-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'prism54-firmware', which does not exist
WARNING: Makefile 'package/linux/Makefile' has a dependency on 'rtl8192su-firmware', which does not exist
Installing all packages from feed manysecured.
Installing package 'edgesec' from manysecured
WARNING: No feed for package 'hostapd' found
WARNING: No feed for package 'dnsmasq' found
WARNING: No feed for package 'libuuid' found
WARNING: No feed for package 'libuci' found
WARNING: No feed for package 'libsqlite3' found
WARNING: No feed for package 'libpcap' found
```
so the missing index error dissapeared. But still compiles nothing.

I will try reinstalling unzipping the SDK archive.

**Comment by mereacre** [comment]
I tried the below instructions and seems to be compiling:
```bash
echo "src-git manysecured https://github.com/nqminds/manysecured-openwrt-packages.git" >> feeds.conf.default
./scripts/feeds update
./scripts/feeds install -a -p manysecured
make defconfig
make
```

**Comment by aloisklink** [comment]
Awesome sauce!

Remember that these instructions won't work for Turris OS, since it's got some patches that changes packaging very slightly. You can use https://github.com/nqminds/many-secured/tree/main/deployment for Turris OS.

And feel free to approve/merge this when you want!

**Review by mereacre — APPROVED** [review]
Great.

**Pull request merged**
